name: Integration Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - "deploy/**"
      - "examples/**"
      - "logos/**"
      - "**.md"
      - "**.txt"
      - "**.ya?ml"
  pull_request:
    paths-ignore:
      - "deploy/**"
      - "examples/**"
      - "logos/**"
      - "**.md"
      - "**.txt"
      - "**.ya?ml"
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Cache binary
        id: cache
        uses: actions/cache@v3
        with:
          path: bin/flipt
          key: ${{ runner.os }}-flipt

      - uses: actions/setup-go@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          go-version: "1.17.x"

      - uses: actions/setup-node@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ui/package-lock.json

      - uses: arduino/setup-task@v1
        if: steps.cache.outputs.cache-hit != 'true'

      - uses: actions/cache@v3
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build the binary
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          task

  api:
    needs: setup
    name: Test API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/integration-test
        with:
          args: ./test/api.sh

  cli:
    needs: setup
    name: Test CLI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/integration-test
        with:
          args: ./test/cli.bats

  ui:
    needs: setup
    name: Test CLI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/integration-test
        with:
          args: ./test/ui.sh
