name: Integration Tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - "deploy/**"
      - "examples/**"
      - "logos/**"
      - "**.md"
      - "**.txt"
      - "**.ya?ml"
  pull_request:
    paths-ignore:
      - "deploy/**"
      - "examples/**"
      - "logos/**"
      - "**.md"
      - "**.txt"
      - "**.ya?ml"
  workflow_dispatch:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "1.17.x"

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: ui/package-lock.json

      - uses: arduino/setup-task@v1

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build the binary
        run: |
          task

      - name: Upload the binary
        uses: actions/upload-artifact@v3
        with:
          name: flipt
          path: ./bin/flipt
          if-no-files-found: error
          retention-days: 1

  api:
    needs: setup
    name: Test API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: flipt
          path: ./bin/flipt

      - name: Run API tests
        uses: ./.github/actions/integration-test
        with:
          args: ./test/api.sh

  cli:
    needs: setup
    name: Test CLI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: flipt
          path: ./bin/flipt

      - name: Run CLI tests
        uses: ./.github/actions/integration-test
        with:
          args: ./test/cli.bats

  ui:
    needs: setup
    name: Test UI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: flipt
          path: ./bin/flipt

      - name: Run UI tests
        uses: ./.github/actions/integration-test
        with:
          args: ./test/ui.sh
